spring.application.name=portafolio


# Puerto del servidor
server.port=8080

# Configuración PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/portafolio_elena
spring.datasource.username=postgres
spring.datasource.password=exit

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
