spring.application.name=portafolio

# Puerto del servidor
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/portafolio_elena
spring.datasource.username=postgres
spring.datasource.password=exit
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.secret=${JWT_SECRET}

# Debug Security
logging.level.org.springframework.security=DEBUG

spring.mail.username=domingosamisa@gmail.com
spring.mail.password=lpfdiuuloofyhwlp